In [1]:
import numpy as np
import pandas as pd


In [2]:
d = [['male',29,'yes'],['male',35,'no'], ['female',24,'yes'],['male',18,'no'],['female',22,'yes'],['female',38,'yes'],['male',28,'no'],['female',18,'no']]
df= pd.DataFrame(d,columns=['Gender','Age','Creditcard?'])

In [3]:
df

Gender  Age Creditcard?
0    male   29         yes
1    male   35          no
2  female   24         yes
3    male   18          no
4  female   22         yes
5  female   38         yes
6    male   28          no
7  female   18          no

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Gender       8 non-null      object
 1   Age          8 non-null      int64 
 2   Creditcard?  8 non-null      object
dtypes: int64(1), object(2)
memory usage: 320.0+ bytes


In [5]:
#converting into categorical columns
for features in df.columns:
    if df[features].dtype =="object":
        df[features] = pd.Categorical(df[features])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   Gender       8 non-null      category
 1   Age          8 non-null      int64   
 2   Creditcard?  8 non-null      category
dtypes: category(2), int64(1)
memory usage: 400.0 bytes


In [6]:
#using OneHotEncoding
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
value = ohe.fit_transform(df)

In [7]:
print(value)

[[0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [8]:
#Using get_dummies
new_df = pd.get_dummies(df)
new_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              8 non-null      int64
 1   Gender_female    8 non-null      uint8
 2   Gender_male      8 non-null      uint8
 3   Creditcard?_no   8 non-null      uint8
 4   Creditcard?_yes  8 non-null      uint8
dtypes: int64(1), uint8(4)
memory usage: 224.0 bytes


In [9]:
new_df

Age  Gender_female  Gender_male  Creditcard?_no  Creditcard?_yes
0   29              0            1               0                1
1   35              0            1               1                0
2   24              1            0               0                1
3   18              0            1               1                0
4   22              1            0               0                1
5   38              1            0               0                1
6   28              0            1               1                0
7   18              1            0               1                0

In [10]:
#using Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
values = oe.fit_transform(df)
print(values)

[[1. 4. 1.]
 [1. 5. 0.]
 [0. 2. 1.]
 [1. 0. 0.]
 [0. 1. 1.]
 [0. 6. 1.]
 [1. 3. 0.]
 [0. 0. 0.]]


In [11]:
for feature in df.columns:
    if df[feature].dtype.name =="category":
        print(pd.value_counts(df[feature]))

male      4
female    4
Name: Gender, dtype: int64
yes    4
no     4
Name: Creditcard?, dtype: int64


In [12]:
#Converting to numerical by find and replace method
replacedata = {"Gender": {"male":1,"female":2},
              "Creditcard?": {"yes":1,"no":0}
              }

In [13]:
replacedata

{'Gender': {'male': 1, 'female': 2}, 'Creditcard?': {'yes': 1, 'no': 0}}

In [14]:
new_df = df.replace(replacedata)

In [15]:
new_df

Gender  Age  Creditcard?
0       1   29            1
1       1   35            0
2       2   24            1
3       1   18            0
4       2   22            1
5       2   38            1
6       1   28            0
7       2   18            0

In [16]:
# Converting Categorical values using LabelEncoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le_df = df.copy()
le_df['Creditcard?'] = le.fit_transform(le_df['Creditcard?'])


In [17]:
le_df

Gender  Age  Creditcard?
0    male   29            1
1    male   35            0
2  female   24            1
3    male   18            0
4  female   22            1
5  female   38            1
6    male   28            0
7  female   18            0